# Generated by Django 5.1.2 on 2024-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=255),
        ),
    ]
