# Generated by Django 5.1.2 on 2024-12-04 06:26

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_alter_bid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='status',
        ),
        migrations.AddField(
            model_name='bid',
            name='state',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='ACCEPTED', max_length=50),
        ),
    ]
