# Generated by Django 5.1.2 on 2024-12-04 07:03

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_remove_bid_status_bid_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='state',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=50),
        ),
    ]
