# Generated by Django 5.1.2 on 2024-10-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_rename_bid_amount_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='is_sold',
            new_name='is_last_bid',
        ),
    ]
