# Generated by Django 5.1.2 on 2024-10-21 10:06

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('mobile_name', models.CharField(max_length=255)),
                ('mobile_company', models.CharField(max_length=255)),
                ('mobile_description', models.TextField()),
                ('mobile_condition', models.CharField(choices=[('refurbished', 'Refurbished'), ('new', 'New'), ('old', 'Old')], max_length=20)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
