# Generated by Django 5.1.2 on 2024-10-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile_name',
            new_name='name',
        ),
    ]
