# Generated by Django 5.1.2 on 2024-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_mobile_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='sold_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
