# Generated by Django 5.1.2 on 2024-12-03 13:00

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='state',
            field=django_fsm.FSMField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=50),
        ),
    ]
