# Generated by Django 5.1.2 on 2024-12-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_mobile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='state',
        ),
    ]
