# Generated by Django 5.1.2 on 2024-10-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='mobiles.mobile'),
        ),
    ]
