# Generated by Django 5.1.2 on 2024-10-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='amount',
        ),
    ]
